### ISSUE TITLE
Wrong path in docker/docker-compose.yml

### ISSUE THREAD

**Issue by CrazyFluffyPony** [GIScience/openrouteservice#1354]
There is a wrong path in the [docker/docker-compose.yml](https://github.com/GIScience/openrouteservice/tree/master/docker/docker-compose.yml) file:

LINE 21
```yaml
      #- ./your_osm.pbf:/home/ors/ors-core/data/osm_file.pbf
```

should be

```yaml
      #- ./your_osm.pbf:/home/ors/data/osm_file.pbf
```

With the original yml file, i got the error
```
ors-app  | Caused by: java.lang.IllegalStateException: Your specified OSM file does not exist:/home/ors/data/osm_file.pbf
```

but with my changed path, its working fine.

#### My version and config
Win 10 64bit with Docker Desktop installed

git clone openrouteservice @ [e37f104](https://github.com/GIScience/openrouteservice/commit/e37f10457b4ec151598763bd4f961d161fa52898)

adjust docker-compose.yml

run docker compose up

adjust conf/ors-config.json

run docker compose up --build

#### Other info

i already used v6.8.0 successfully so i think i roughly know what i'm doing

---

Thank you for this project, it is awesome!

**Comment by CrazyFluffyPony** [comment]
Looks like all the paths including `ors-core` are affected too

```yml
      - ./graphs:/home/ors/ors-core/data/graphs
      - ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./logs/ors:/home/ors/ors-core/logs/ors
```

**Comment by MichaelsJP** [comment]
@CrazyFluffyPony Thanks for reporting. Please make sure to pull the latest images before you start the container:

```
docker-compose pull
```

**Comment by CrazyFluffyPony** [comment]
> @CrazyFluffyPony Thanks for reporting. Please make sure to pull the latest images before you start the container:
> 
> ```
> docker-compose pull
> ```

yeah i did

**Comment by MichaelsJP** [comment]
The paths changed in v6.8.2. It's not ideal, but it was needed due to tomcat overwriting user permissions leading to admin only containers.

As you can see here: https://github.com/GIScience/openrouteservice/blob/master/Dockerfile#L53 the config reads the pbf from `/home/ors/ors-core/data/osm_file.pbf`. 


Please try to follow the tips in the following thread, where a comparable problem occurred and could be resolved:
- https://github.com/GIScience/openrouteservice/issues/1331

You can try the following (on a fresh start, it works for me):

docker commands
```bash
> docker-compose down
> sudo rm -rf graphs conf data
> docker-compose pull
> docker-compose up --force-recreate -d && docker-compose logs -ft
```


docker-compose.yml
```yml
services:
  ors-app:
    container_name: ors-app
    ports:
      - "8080:8080"
      - "9001:9001"
    image: openrouteservice/openrouteservice:v6.8.3
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ./graphs:/home/ors/ors-core/data/graphs
      - ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./logs/ors:/home/ors/ors-core/logs/ors
      - ./logs/tomcat:/home/ors/tomcat/logs
      - ./conf:/home/ors/ors-conf
      #- ./your_osm_file.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=True  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

Switch ` BUILD_GRAPHS=True ` to False afterwards.
