### ISSUE TITLE
Update setup-java action and define OpenJDK

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1373]
The current workflow uses setup-java@v1 and uses the default java. This gets sometimes stuck at resolving dependencies. This is known. The advice is to use setup-java@v2 and define openjdk.

```yml
- name: Set up JDK 17
  uses: actions/setup-java@v2
  with:
    distribution: 'temurin'
    java-version: '17'
```
