### ISSUE TITLE
during health check ups "status": "not ready"

### ISSUE THREAD

**Issue by Boom199801** [GIScience/openrouteservice#1677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

http://localhost:8080/ors/v2/health

### POST Request Body

```JSON
{
  "status": "not ready"
}
```

### Response

<details><summary>Response</summary>

```JSON

PASTE HERE

```
</details>

### Current behavior

```
docker compose up -d
[+] Running 1/1
 ⠿ Container ors-app  Started                                                                                                                                                                                                   1.6s
[root@bigdata-gpu01 docker]# docker logs -f ors-app
Running container as user root with id 0
ORS Path: /home/ors
Catalina Path: /home/ors/tomcat
### openrouteservice configuration ###
Copy ors-config.yml

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.6)

04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.Application                      ]   Starting Application v8.0-SNAPSHOT using Java 17.0.7 with PID 1 (/home/ors/tomcat/webapps/ors/WEB-INF/classes started by root in /home/ors)
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.Application                      ]   The following 1 profile is active: "default"
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   Configuration file set by environment variable.
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   Loaded file 'ors-conf/ors-config.yml'
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   Environment variables overriding openrouteservice configuration parameters detected: 
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   ORS_CONFIG_LOCATION=ors-conf/ors-config.yml
04 Feb 04:48:20 INFO                                                  main [ o.h.o.a.ORSEnvironmentPostProcessor      ]   
log4j:WARN No appenders could be found for logger (io.micrometer.common.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
04 Feb 04:48:24 INFO                                                  main [ o.h.o.a.Application                      ]   Started Application in 4.304 seconds (process running for 10.995)
```

### Expected behavior

during health check ups "status": "not ready"  

The steps used are:
```
git clone https://github.com/GIScience/openrouteservice.git
cd openrouteservice
export LATEST_ORS_RELEASE=$(git describe --tags --abbrev=0); 
git checkout $LATEST_ORS_RELEASE
docker compose up -d
```

docker-compose:
```
version: '2.4'
services:
  ors-app:
    container_name: ors-app
    ports:
      - "31223:8080"
      - "31224:9001"
    image: openrouteservice/openrouteservice:nightly
    user: "${UID:-0}:${GID:-0}"
#    build:
#      context: ../
#      args:
#        ORS_CONFIG: ./openrouteservice/src/main/resources/ors-config-sample.json
#        OSM_FILE: ./openrouteservice/src/main/files/heidelberg.osm.gz
    volumes:
      - ./graphs:/home/ors/ors-core/data/graphs
      - ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./logs/ors:/home/ors/ors-core/logs/ors
      - ./logs/tomcat:/home/ors/tomcat/logs
      - ./conf:/home/ors/ors-conf
      - /nfs4/nfs/dazhao_model/wjg/china-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

### Openrouteservice Version

nightly
