### ISSUE TITLE
Integer Max Value Limit of [max_visited_nodes]

### ISSUE THREAD

**Issue by erdogansonmez** [GIScience/openrouteservice#1979]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Hello everyone, i need increase max_visited_nodes more than integer max value. I got this error:

```json
{"code":3,"error":"Unable to compute a distance/duration matrix: Search exceeds the limit of visited nodes."}
```
```yml
engine:
    profile_default:
      service:
        maximum_distance: 2147483647
        maximum_routes: 160000
        maximum_distance_dynamic_weights: 2147483647
        maximum_distance_avoid_areas: 2147483647
        maximum_waypoints: 2147483647
        maximum_snapping_radius: 1000
        maximum_distance_alternative_routes: 2147483647
        maximum_distance_round_trip_routes: 2147483647
        maximum_visited_nodes: 2147483647
```

When i increase the maximum_visited_nodes more than “2147483647” error throwed from java integer and long type converting.

### Proposed solution

I Need increase the maximum_visited_nodes for calculating huge operations, Integer Max Value not enough for me.

### Forum Topic Link

https://ask.openrouteservice.org/t/engine-limit-values-with-integer-max-value/7104
